heap-assignment-tracing-agent.so: main.cpp
	g++ main.cpp -o heap-assignment-tracing-agent.so -I/usr/lib/jvm/graalvm-ce-java17-22.3.0/include/ -I/usr/lib/jvm/graalvm-ce-java17-22.3.0/include/linux/ -shared

clean:
	rm heap-assignment-tracing-agent.so