
var loadWASM = (() => {
  var _scriptDir = import.meta.url;
  
  return (
async function(loadWASM = {})  {

var g;g||(g=typeof loadWASM !== 'undefined' ? loadWASM : {});var aa,k;g.ready=new Promise(function(a,b){aa=a;k=b});var ba=Object.assign({},g),ca="./this.program",da=(a,b)=>{throw b;},ea="object"==typeof window,n="function"==typeof importScripts,x="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,y="",fa,z,ha;
if(x){const {createRequire:a}=await import("module");var require=a(import.meta.url),fs=require("fs"),ia=require("path");n?y=ia.dirname(y)+"/":y=require("url").fileURLToPath(new URL("./",import.meta.url));fa=(b,c)=>{b=b.startsWith("file://")?new URL(b):ia.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")};ha=b=>{b=fa(b,!0);b.buffer||(b=new Uint8Array(b));return b};z=(b,c,d)=>{b=b.startsWith("file://")?new URL(b):ia.normalize(b);fs.readFile(b,function(e,h){e?d(e):
c(h.buffer)})};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);process.on("uncaughtException",function(b){if(!("unwind"===b||b instanceof ja||b.context instanceof ja))throw b;});if(15>process.versions.node.split(".")[0])process.on("unhandledRejection",function(b){throw b;});da=(b,c)=>{process.exitCode=b;throw c;};g.inspect=function(){return"[Emscripten Module object]"}}else if(ea||n)n?y=self.location.href:"undefined"!=typeof document&&document.currentScript&&(y=
document.currentScript.src),_scriptDir&&(y=_scriptDir),0!==y.indexOf("blob:")?y=y.substr(0,y.replace(/[?#].*/,"").lastIndexOf("/")+1):y="",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},n&&(ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),z=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):
c()};d.onerror=c;d.send(null)};var ka=g.print||console.log.bind(console),A=g.printErr||console.warn.bind(console);Object.assign(g,ba);ba=null;g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);var C;g.wasmBinary&&(C=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&D("no native wasm support detected");var la,ma=!1,na="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function F(a,b){for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&na)return na.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|h);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|l:(e&7)<<18|h<<12|l<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c}
function oa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var l=a.charCodeAt(h);if(55296<=l&&57343>=l){var q=a.charCodeAt(++h);l=65536+((l&1023)<<10)|q&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}
function pa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var G,H,I,J;function qa(){var a=la.buffer;g.HEAP8=G=new Int8Array(a);g.HEAP16=new Int16Array(a);g.HEAP32=I=new Int32Array(a);g.HEAPU8=H=new Uint8Array(a);g.HEAPU16=new Uint16Array(a);g.HEAPU32=J=new Uint32Array(a);g.HEAPF32=new Float32Array(a);g.HEAPF64=new Float64Array(a)}var K,ra=[],sa=[],ta=[];function ua(){var a=g.preRun.shift();ra.unshift(a)}
var L=0,va=null,N=null;function D(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";A(a);ma=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");k(a);throw a;}function wa(a){return a.startsWith("data:application/octet-stream;base64,")}var O;if(g.locateFile){if(O="causality-query.wasm",!wa(O)){var xa=O;O=g.locateFile?g.locateFile(xa,y):y+xa}}else O=(new URL("causality-query.wasm",import.meta.url)).href;
function ya(a){try{if(a==O&&C)return new Uint8Array(C);if(ha)return ha(a);throw"both async and sync fetching of the wasm failed";}catch(b){D(b)}}
function za(a){if(!C&&(ea||n)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(function(){return ya(a)});if(z)return new Promise(function(b,c){z(a,function(d){b(new Uint8Array(d))},c)})}return Promise.resolve().then(function(){return ya(a)})}
function Aa(a,b,c){return za(a).then(function(d){return WebAssembly.instantiate(d,b)}).then(function(d){return d}).then(c,function(d){A("failed to asynchronously prepare wasm: "+d);D(d)})}
function Ba(a,b){var c=O;return C||"function"!=typeof WebAssembly.instantiateStreaming||wa(c)||c.startsWith("file://")||x||"function"!=typeof fetch?Aa(c,a,b):fetch(c,{credentials:"same-origin"}).then(function(d){return WebAssembly.instantiateStreaming(d,a).then(b,function(e){A("wasm streaming compile failed: "+e);A("falling back to ArrayBuffer instantiation");return Aa(c,a,b)})})}var P,Ca;function ja(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
function Da(a){for(;0<a.length;)a.shift()(g)}function Ea(a){this.P=a-24;this.sa=function(b){J[this.P+4>>2]=b};this.pa=function(b){J[this.P+8>>2]=b};this.qa=function(){I[this.P>>2]=0};this.oa=function(){G[this.P+12>>0]=0};this.ra=function(){G[this.P+13>>0]=0};this.T=function(b,c){this.na();this.sa(b);this.pa(c);this.qa();this.oa();this.ra()};this.na=function(){J[this.P+16>>2]=0}}var Fa=0,Ga={};
function Ha(){if(!Ia){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Ga)void 0===Ga[b]?delete a[b]:a[b]=Ga[b];var c=[];for(b in a)c.push(b+"="+a[b]);Ia=c}return Ia}
var Ia,Ja=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ka=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ja(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},La=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Ma=
a=>{if("/"===a)return"/";a=Ka(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function Na(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return()=>{crypto.getRandomValues(a);return a[0]}}if(x)try{var b=require("crypto");return()=>b.randomBytes(1)[0]}catch(c){}return()=>D("randomDevice")}
function Oa(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ja(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}function Pa(a,b){var c=Array(pa(a)+1);a=oa(a,c,0,c.length);b&&(c.length=a);return c}var Qa=[];function Ra(a,b){Qa[a]={input:[],output:[],U:b};Sa(a,Ta)}
var Ta={open:function(a){var b=Qa[a.node.rdev];if(!b)throw new Q(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.U.fsync(a.tty)},fsync:function(a){a.tty.U.fsync(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.U.ja)throw new Q(60);for(var e=0,h=0;h<d;h++){try{var l=a.tty.U.ja(a.tty)}catch(q){throw new Q(29);}if(void 0===l&&0===e)throw new Q(6);if(null===l||void 0===l)break;e++;b[c+h]=l}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.U.aa)throw new Q(60);try{for(var e=
0;e<d;e++)a.tty.U.aa(a.tty,b[c+e])}catch(h){throw new Q(29);}d&&(a.node.timestamp=Date.now());return e}},Ua={ja:function(a){if(!a.input.length){var b=null;if(x){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==
b&&(b+="\n"));if(!b)return null;a.input=Pa(b,!0)}return a.input.shift()},aa:function(a,b){null===b||10===b?(ka(F(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(ka(F(a.output,0)),a.output=[])}},Va={aa:function(a,b){null===b||10===b?(A(F(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(A(F(a.output,0)),a.output=[])}},R={J:null,M:function(){return R.createNode(null,"/",16895,0)},createNode:function(a,
b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new Q(63);R.J||(R.J={dir:{node:{N:R.G.N,K:R.G.K,lookup:R.G.lookup,W:R.G.W,rename:R.G.rename,unlink:R.G.unlink,rmdir:R.G.rmdir,readdir:R.G.readdir,symlink:R.G.symlink},stream:{O:R.H.O}},file:{node:{N:R.G.N,K:R.G.K},stream:{O:R.H.O,read:R.H.read,write:R.H.write,ea:R.H.ea,ka:R.H.ka,ma:R.H.ma}},link:{node:{N:R.G.N,K:R.G.K,readlink:R.G.readlink},stream:{}},fa:{node:{N:R.G.N,K:R.G.K},stream:Wa}});c=Xa(a,b,c,d);16384===(c.mode&61440)?(c.G=R.J.dir.node,
c.H=R.J.dir.stream,c.F={}):32768===(c.mode&61440)?(c.G=R.J.file.node,c.H=R.J.file.stream,c.I=0,c.F=null):40960===(c.mode&61440)?(c.G=R.J.link.node,c.H=R.J.link.stream):8192===(c.mode&61440)&&(c.G=R.J.fa.node,c.H=R.J.fa.stream);c.timestamp=Date.now();a&&(a.F[b]=c,a.timestamp=c.timestamp);return c},Ea:function(a){return a.F?a.F.subarray?a.F.subarray(0,a.I):new Uint8Array(a.F):new Uint8Array(0)},ga:function(a,b){var c=a.F?a.F.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,
256)),c=a.F,a.F=new Uint8Array(b),0<a.I&&a.F.set(c.subarray(0,a.I),0))},wa:function(a,b){if(a.I!=b)if(0==b)a.F=null,a.I=0;else{var c=a.F;a.F=new Uint8Array(b);c&&a.F.set(c.subarray(0,Math.min(b,a.I)));a.I=b}},G:{N:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.I:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);
b.ctime=new Date(a.timestamp);b.ta=4096;b.blocks=Math.ceil(b.size/b.ta);return b},K:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&R.wa(a,b.size)},lookup:function(){throw Ya[44];},W:function(a,b,c,d){return R.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Za(b,c)}catch(h){}if(d)for(var e in d.F)throw new Q(55);}delete a.parent.F[a.name];a.parent.timestamp=Date.now();a.name=c;b.F[c]=a;b.timestamp=a.parent.timestamp;
a.parent=b},unlink:function(a,b){delete a.F[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=Za(a,b),d;for(d in c.F)throw new Q(55);delete a.F[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.F)a.F.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=R.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new Q(28);return a.link}},H:{read:function(a,b,c,d,e){var h=a.node.F;if(e>=a.node.I)return 0;a=Math.min(a.node.I-
e,d);if(8<a&&h.subarray)b.set(h.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=h[e+d];return a},write:function(a,b,c,d,e,h){b.buffer===G.buffer&&(h=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.F||a.F.subarray)){if(h)return a.F=b.subarray(c,c+d),a.I=d;if(0===a.I&&0===e)return a.F=b.slice(c,c+d),a.I=d;if(e+d<=a.I)return a.F.set(b.subarray(c,c+d),e),d}R.ga(a,e+d);if(a.F.subarray&&b.subarray)a.F.set(b.subarray(c,c+d),e);else for(h=0;h<d;h++)a.F[e+h]=b[c+h];a.I=Math.max(a.I,e+
d);return d},O:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.I);if(0>b)throw new Q(28);return b},ea:function(a,b,c){R.ga(a.node,b+c);a.node.I=Math.max(a.node.I,b+c)},ka:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new Q(43);a=a.node.F;if(e&2||a.buffer!==G.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;D();b=void 0;if(!b)throw new Q(48);G.set(a,b)}else c=!1,b=a.byteOffset;return{P:b,Da:c}},ma:function(a,
b,c,d){R.H.write(a,b,0,d,c,!1);return 0}}},$a=null,ab={},S=[],bb=1,T=null,cb=!0,Q=null,Ya={},U=(a,b={})=>{a=Oa(a);if(!a)return{path:"",node:null};b=Object.assign({ia:!0,ba:0},b);if(8<b.ba)throw new Q(32);a=a.split("/").filter(l=>!!l);for(var c=$a,d="/",e=0;e<a.length;e++){var h=e===a.length-1;if(h&&b.parent)break;c=Za(c,a[e]);d=Ka(d+"/"+a[e]);c.X&&(!h||h&&b.ia)&&(c=c.X.root);if(!h||b.ha)for(h=0;40960===(c.mode&61440);)if(c=db(d),d=Oa(La(d),c),c=U(d,{ba:b.ba+1}).node,40<h++)throw new Q(32);}return{path:d,
node:c}},eb=a=>{for(var b;;){if(a===a.parent)return a=a.M.la,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},fb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%T.length},Za=(a,b)=>{var c;if(c=(c=gb(a,"x"))?c:a.G.lookup?0:2)throw new Q(c,a);for(c=T[fb(a.id,b)];c;c=c.va){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.G.lookup(a,b)},Xa=(a,b,c,d)=>{a=new hb(a,b,c,d);b=fb(a.parent.id,a.name);a.va=T[b];return T[b]=a},ib={r:0,"r+":2,
w:577,"w+":578,a:1089,"a+":1090},jb=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},gb=(a,b)=>{if(cb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},kb=(a,b)=>{try{return Za(a,b),20}catch(c){}return gb(a,"wx")},lb=()=>{for(var a=0;4096>=a;a++)if(!S[a])return a;throw new Q(33);},mb=a=>{V||(V=function(){this.T={}},V.prototype={},Object.defineProperties(V.prototype,{object:{get:function(){return this.node},
set:function(c){this.node=c}},flags:{get:function(){return this.T.flags},set:function(c){this.T.flags=c}},position:{get:function(){return this.T.position},set:function(c){this.T.position=c}}}));a=Object.assign(new V,a);var b=lb();a.fd=b;return S[b]=a},Wa={open:a=>{a.H=ab[a.node.rdev].H;a.H.open&&a.H.open(a)},O:()=>{throw new Q(70);}},Sa=(a,b)=>{ab[a]={H:b}},nb=(a,b)=>{var c="/"===b,d=!b;if(c&&$a)throw new Q(10);if(!c&&!d){var e=U(b,{ia:!1});b=e.path;e=e.node;if(e.X)throw new Q(10);if(16384!==(e.mode&
61440))throw new Q(54);}b={type:a,Fa:{},la:b,ua:[]};a=a.M(b);a.M=b;b.root=a;c?$a=a:e&&(e.X=b,e.M&&e.M.ua.push(b))},W=(a,b,c)=>{var d=U(a,{parent:!0}).node;a=Ma(a);if(!a||"."===a||".."===a)throw new Q(28);var e=kb(d,a);if(e)throw new Q(e);if(!d.G.W)throw new Q(63);return d.G.W(d,a,b,c)},ob=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);W(a,b|8192,c)},pb=(a,b)=>{if(!Oa(a))throw new Q(44);var c=U(b,{parent:!0}).node;if(!c)throw new Q(44);b=Ma(b);var d=kb(c,b);if(d)throw new Q(d);if(!c.G.symlink)throw new Q(63);
c.G.symlink(c,b,a)},db=a=>{a=U(a).node;if(!a)throw new Q(44);if(!a.G.readlink)throw new Q(28);return Oa(eb(a.parent),a.G.readlink(a))},rb=(a,b)=>{if(""===a)throw new Q(44);if("string"==typeof b){var c=ib[b];if("undefined"==typeof c)throw Error("Unknown file open mode: "+b);b=c}var d=b&64?("undefined"==typeof d?438:d)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Ka(a);try{e=U(a,{ha:!(b&131072)}).node}catch(h){}}c=!1;if(b&64)if(e){if(b&128)throw new Q(20);}else e=W(a,d,0),c=!0;if(!e)throw new Q(44);
8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new Q(54);if(!c&&(d=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==jb(b)||b&512)?31:gb(e,jb(b)):44))throw new Q(d);if(b&512&&!c){d=e;d="string"==typeof d?U(d,{ha:!0}).node:d;if(!d.G.K)throw new Q(63);if(16384===(d.mode&61440))throw new Q(31);if(32768!==(d.mode&61440))throw new Q(28);if(c=gb(d,"w"))throw new Q(c);d.G.K(d,{size:0,timestamp:Date.now()})}b&=-131713;e=mb({node:e,path:eb(e),flags:b,seekable:!0,position:0,
H:e.H,Ca:[],error:!1});e.H.open&&e.H.open(e);!g.logReadFiles||b&1||(qb||(qb={}),a in qb||(qb[a]=1))},sb=(a,b,c)=>{if(null===a.fd)throw new Q(8);if(!a.seekable||!a.H.O)throw new Q(70);if(0!=c&&1!=c&&2!=c)throw new Q(28);a.position=a.H.O(a,b,c);a.Ca=[]},tb=()=>{Q||(Q=function(a,b){this.name="ErrnoError";this.node=b;this.xa=function(c){this.V=c};this.xa(a);this.message="FS error"},Q.prototype=Error(),Q.prototype.constructor=Q,[44].forEach(a=>{Ya[a]=new Q(a);Ya[a].stack="<generic error, no stack>"}))},
ub,vb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},X=(a,b,c)=>{a=Ka("/dev/"+a);var d=vb(!!b,!!c);wb||(wb=64);var e=wb++<<8|0;Sa(e,{open:h=>{h.seekable=!1},close:()=>{c&&c.buffer&&c.buffer.length&&c(10)},read:(h,l,q,u)=>{for(var m=0,t=0;t<u;t++){try{var v=b()}catch(B){throw new Q(29);}if(void 0===v&&0===m)throw new Q(6);if(null===v||void 0===v)break;m++;l[q+t]=v}m&&(h.node.timestamp=Date.now());return m},write:(h,l,q,u)=>{for(var m=0;m<u;m++)try{c(l[q+m])}catch(t){throw new Q(29);}u&&(h.node.timestamp=
Date.now());return m}});ob(a,d,e)},wb,xb={},V,qb;function yb(a){a=S[a];if(!a)throw new Q(8);return a}function zb(a){return 0===a%4&&(0!==a%100||0===a%400)}var Ab=[31,29,31,30,31,30,31,31,30,31,30,31],Bb=[31,28,31,30,31,30,31,31,30,31,30,31];
function Cb(a,b,c,d){function e(f,p,r){for(f="number"==typeof f?f.toString():f||"";f.length<p;)f=r[0]+f;return f}function h(f,p){return e(f,p,"0")}function l(f,p){function r(E){return 0>E?-1:0<E?1:0}var w;0===(w=r(f.getFullYear()-p.getFullYear()))&&0===(w=r(f.getMonth()-p.getMonth()))&&(w=r(f.getDate()-p.getDate()));return w}function q(f){switch(f.getDay()){case 0:return new Date(f.getFullYear()-1,11,29);case 1:return f;case 2:return new Date(f.getFullYear(),0,3);case 3:return new Date(f.getFullYear(),
0,2);case 4:return new Date(f.getFullYear(),0,1);case 5:return new Date(f.getFullYear()-1,11,31);case 6:return new Date(f.getFullYear()-1,11,30)}}function u(f){var p=f.R;for(f=new Date((new Date(f.S+1900,0,1)).getTime());0<p;){var r=f.getMonth(),w=(zb(f.getFullYear())?Ab:Bb)[r];if(p>w-f.getDate())p-=w-f.getDate()+1,f.setDate(1),11>r?f.setMonth(r+1):(f.setMonth(0),f.setFullYear(f.getFullYear()+1));else{f.setDate(f.getDate()+p);break}}r=new Date(f.getFullYear()+1,0,4);p=q(new Date(f.getFullYear(),0,
4));r=q(r);return 0>=l(p,f)?0>=l(r,f)?f.getFullYear()+1:f.getFullYear():f.getFullYear()-1}var m=I[d+40>>2];d={Aa:I[d>>2],za:I[d+4>>2],Y:I[d+8>>2],da:I[d+12>>2],Z:I[d+16>>2],S:I[d+20>>2],L:I[d+24>>2],R:I[d+28>>2],Ga:I[d+32>>2],ya:I[d+36>>2],Ba:m?m?F(H,m):"":""};c=c?F(H,c):"";m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y",
"%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var t in m)c=c.replace(new RegExp(t,"g"),m[t]);var v="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),B="January February March April May June July August September October November December".split(" ");m={"%a":function(f){return v[f.L].substring(0,3)},"%A":function(f){return v[f.L]},"%b":function(f){return B[f.Z].substring(0,3)},
"%B":function(f){return B[f.Z]},"%C":function(f){return h((f.S+1900)/100|0,2)},"%d":function(f){return h(f.da,2)},"%e":function(f){return e(f.da,2," ")},"%g":function(f){return u(f).toString().substring(2)},"%G":function(f){return u(f)},"%H":function(f){return h(f.Y,2)},"%I":function(f){f=f.Y;0==f?f=12:12<f&&(f-=12);return h(f,2)},"%j":function(f){for(var p=0,r=0;r<=f.Z-1;p+=(zb(f.S+1900)?Ab:Bb)[r++]);return h(f.da+p,3)},"%m":function(f){return h(f.Z+1,2)},"%M":function(f){return h(f.za,2)},"%n":function(){return"\n"},
"%p":function(f){return 0<=f.Y&&12>f.Y?"AM":"PM"},"%S":function(f){return h(f.Aa,2)},"%t":function(){return"\t"},"%u":function(f){return f.L||7},"%U":function(f){return h(Math.floor((f.R+7-f.L)/7),2)},"%V":function(f){var p=Math.floor((f.R+7-(f.L+6)%7)/7);2>=(f.L+371-f.R-2)%7&&p++;if(p)53==p&&(r=(f.L+371-f.R)%7,4==r||3==r&&zb(f.S)||(p=1));else{p=52;var r=(f.L+7-f.R-1)%7;(4==r||5==r&&zb(f.S%400-1))&&p++}return h(p,2)},"%w":function(f){return f.L},"%W":function(f){return h(Math.floor((f.R+7-(f.L+6)%
7)/7),2)},"%y":function(f){return(f.S+1900).toString().substring(2)},"%Y":function(f){return f.S+1900},"%z":function(f){f=f.ya;var p=0<=f;f=Math.abs(f)/60;return(p?"+":"-")+String("0000"+(f/60*100+f%60)).slice(-4)},"%Z":function(f){return f.Ba},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(t in m)c.includes(t)&&(c=c.replace(new RegExp(t,"g"),m[t](d)));c=c.replace(/\0\0/g,"%");t=Pa(c,!1);if(t.length>b)return 0;G.set(t,a);return t.length-1}
function Db(a,b,c,d){var e={string:m=>{var t=0;if(null!==m&&void 0!==m&&0!==m){var v=(m.length<<2)+1;t=Eb(v);oa(m,H,t,v)}return t},array:m=>{var t=Eb(m.length);G.set(m,t);return t}};a=g["_"+a];var h=[],l=0;if(d)for(var q=0;q<d.length;q++){var u=e[c[q]];u?(0===l&&(l=Fb()),h[q]=u(d[q])):h[q]=d[q]}c=a.apply(null,h);return c=function(m){0!==l&&Gb(l);return"string"===b?m?F(H,m):"":"boolean"===b?!!m:m}(c)}var Y=[];function Hb(a){var b=Y[a];b||(a>=Y.length&&(Y.length=a+1),Y[a]=b=K.get(a));return b}
var Z=void 0,Ib=[];function hb(a,b,c,d){a||(a=this);this.parent=a;this.M=a.M;this.X=null;this.id=bb++;this.name=b;this.mode=c;this.G={};this.H={};this.rdev=d}Object.defineProperties(hb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});tb();T=Array(4096);nb(R,"/");W("/tmp",16895,0);W("/home",16895,0);W("/home/web_user",16895,0);
(()=>{W("/dev",16895,0);Sa(259,{read:()=>0,write:(b,c,d,e)=>e});ob("/dev/null",259);Ra(1280,Ua);Ra(1536,Va);ob("/dev/tty",1280);ob("/dev/tty1",1536);var a=Na();X("random",a);X("urandom",a);W("/dev/shm",16895,0);W("/dev/shm/tmp",16895,0)})();(()=>{W("/proc",16895,0);var a=W("/proc/self",16895,0);W("/proc/self/fd",16895,0);nb({M:()=>{var b=Xa(a,"fd",16895,73);b.G={lookup:(c,d)=>{var e=S[+d];if(!e)throw new Q(8);c={parent:null,M:{la:"fake"},G:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var Jb={a:function(a,b,c){(new Ea(a)).T(b,c);Fa++;throw a;},f:function(){return!0},c:function(){D("")},g:function(){return Date.now()},i:function(a,b,c){H.copyWithin(a,b,b+c)},h:function(a){var b=H.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math,h=e.min;d=Math.max(a,d);d+=(65536-d%65536)%65536;a:{var l=la.buffer;try{la.grow(h.call(e,2147483648,d)-l.byteLength+65535>>>16);qa();var q=1;break a}catch(u){}q=void 0}if(q)return!0}return!1},
l:function(a,b){var c=0;Ha().forEach(function(d,e){var h=b+c;e=J[a+4*e>>2]=h;for(h=0;h<d.length;++h)G[e++>>0]=d.charCodeAt(h);G[e>>0]=0;c+=d.length+1});return 0},m:function(a,b){var c=Ha();J[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});J[b>>2]=d;return 0},n:function(a){if(!noExitRuntime){if(g.onExit)g.onExit(a);ma=!0}da(a,new ja(a))},d:function(a){try{var b=yb(a);if(null===b.fd)throw new Q(8);b.$&&(b.$=null);try{b.H.close&&b.H.close(b)}catch(c){throw c;}finally{S[b.fd]=null}b.fd=null;
return 0}catch(c){if("undefined"==typeof xb||"ErrnoError"!==c.name)throw c;return c.V}},e:function(a,b,c,d){try{a:{var e=yb(a);a=b;for(var h,l=b=0;l<c;l++){var q=J[a>>2],u=J[a+4>>2];a+=8;var m=e,t=q,v=u,B=h,f=G;if(0>v||0>B)throw new Q(28);if(null===m.fd)throw new Q(8);if(1===(m.flags&2097155))throw new Q(8);if(16384===(m.node.mode&61440))throw new Q(31);if(!m.H.read)throw new Q(28);var p="undefined"!=typeof B;if(!p)B=m.position;else if(!m.seekable)throw new Q(70);var r=m.H.read(m,f,t,v,B);p||(m.position+=
r);var w=r;if(0>w){var E=-1;break a}b+=w;if(w<u)break;"undefined"!==typeof h&&(h+=w)}E=b}J[d>>2]=E;return 0}catch(M){if("undefined"==typeof xb||"ErrnoError"!==M.name)throw M;return M.V}},j:function(a,b,c,d,e){try{b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return 61;var h=yb(a);sb(h,b,d);Ca=[h.position>>>0,(P=h.position,1<=+Math.abs(P)?0<P?(Math.min(+Math.floor(P/4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];I[e>>2]=Ca[0];I[e+4>>2]=Ca[1];h.$&&
0===b&&0===d&&(h.$=null);return 0}catch(l){if("undefined"==typeof xb||"ErrnoError"!==l.name)throw l;return l.V}},b:function(a,b,c,d){try{a:{var e=yb(a);a=b;for(var h,l=b=0;l<c;l++){var q=J[a>>2],u=J[a+4>>2];a+=8;var m=e,t=q,v=u,B=h,f=G;if(0>v||0>B)throw new Q(28);if(null===m.fd)throw new Q(8);if(0===(m.flags&2097155))throw new Q(8);if(16384===(m.node.mode&61440))throw new Q(31);if(!m.H.write)throw new Q(28);m.seekable&&m.flags&1024&&sb(m,0,2);var p="undefined"!=typeof B;if(!p)B=m.position;else if(!m.seekable)throw new Q(70);
var r=m.H.write(m,f,t,v,B,void 0);p||(m.position+=r);var w=r;if(0>w){var E=-1;break a}b+=w;"undefined"!==typeof h&&(h+=w)}E=b}J[d>>2]=E;return 0}catch(M){if("undefined"==typeof xb||"ErrnoError"!==M.name)throw M;return M.V}},k:function(a,b,c,d){return Cb(a,b,c,d)}};
(function(){function a(c){c=c.exports;g.asm=c;la=g.asm.o;qa();K=g.asm.z;sa.unshift(g.asm.p);L--;g.monitorRunDependencies&&g.monitorRunDependencies(L);if(0==L&&(null!==va&&(clearInterval(va),va=null),N)){var d=N;N=null;d()}return c}var b={a:Jb};L++;g.monitorRunDependencies&&g.monitorRunDependencies(L);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){A("Module.instantiateWasm callback failed with error: "+c),k(c)}Ba(b,function(c){a(c.instance)}).catch(k);return{}})();
g._CausalityGraph_init=function(){return(g._CausalityGraph_init=g.asm.q).apply(null,arguments)};g._CausalityGraph_simulatePurge=function(){return(g._CausalityGraph_simulatePurge=g.asm.r).apply(null,arguments)};g._CausalityGraph_simulatePurgeDetailed=function(){return(g._CausalityGraph_simulatePurgeDetailed=g.asm.s).apply(null,arguments)};g._CausalityGraph_simulatePurgesBatched=function(){return(g._CausalityGraph_simulatePurgesBatched=g.asm.t).apply(null,arguments)};
g._DetailedSimulationResult_getReachabilityHyperpath=function(){return(g._DetailedSimulationResult_getReachabilityHyperpath=g.asm.u).apply(null,arguments)};var Kb=g._malloc=function(){return(Kb=g._malloc=g.asm.v).apply(null,arguments)};g._SimulationResult_getMethodHistory=function(){return(g._SimulationResult_getMethodHistory=g.asm.w).apply(null,arguments)};g._IncrementalSimulationResult_simulateNext=function(){return(g._IncrementalSimulationResult_simulateNext=g.asm.x).apply(null,arguments)};
g._Deletable_delete=function(){return(g._Deletable_delete=g.asm.y).apply(null,arguments)};g._free=function(){return(g._free=g.asm.A).apply(null,arguments)};function Fb(){return(Fb=g.asm.B).apply(null,arguments)}function Gb(){return(Gb=g.asm.C).apply(null,arguments)}function Eb(){return(Eb=g.asm.D).apply(null,arguments)}g.cwrap=function(a,b,c,d){var e=!c||c.every(h=>"number"===h||"boolean"===h);return"string"!==b&&e&&!d?g["_"+a]:function(){return Db(a,b,c,arguments)}};
g.addFunction=function(a,b){if(!Z){Z=new WeakMap;var c=K.length;if(Z)for(var d=0;d<0+c;d++){var e=Hb(d);e&&Z.set(e,d)}}if(c=Z.get(a)||0)return c;if(Ib.length)c=Ib.pop();else{try{K.grow(1)}catch(q){if(!(q instanceof RangeError))throw q;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}c=K.length-1}try{d=c,K.set(d,a),Y[d]=K.get(d)}catch(q){if(!(q instanceof TypeError))throw q;if("function"==typeof WebAssembly.Function){d=WebAssembly.Function;e={i:"i32",j:"i32",f:"f32",d:"f64",p:"i32"};for(var h=
{parameters:[],results:"v"==b[0]?[]:[e[b[0]]]},l=1;l<b.length;++l)h.parameters.push(e[b[l]]),"j"===b[l]&&h.parameters.push("i32");b=new d(h,a)}else{d=[1];e=b.slice(0,1);b=b.slice(1);h={i:127,p:127,j:126,f:125,d:124};d.push(96);l=b.length;128>l?d.push(l):d.push(l%128|128,l>>7);for(l=0;l<b.length;++l)d.push(h[b[l]]);"v"==e?d.push(0):d.push(1,h[e]);b=[0,97,115,109,1,0,0,0,1];e=d.length;128>e?b.push(e):b.push(e%128|128,e>>7);b.push.apply(b,d);b.push(2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(new Uint8Array(b));
b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f}d=c;K.set(d,b);Y[d]=K.get(d)}Z.set(a,c);return c};g.removeFunction=function(a){Z.delete(Hb(a));Ib.push(a)};g.allocateUTF8=function(a){var b=pa(a)+1,c=Kb(b);c&&oa(a,G,c,b);return c};var Lb;N=function Mb(){Lb||Nb();Lb||(N=Mb)};
function Nb(){function a(){if(!Lb&&(Lb=!0,g.calledRun=!0,!ma)){g.noFSInit||ub||(ub=!0,tb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?X("stdin",g.stdin):pb("/dev/tty","/dev/stdin"),g.stdout?X("stdout",null,g.stdout):pb("/dev/tty","/dev/stdout"),g.stderr?X("stderr",null,g.stderr):pb("/dev/tty1","/dev/stderr"),rb("/dev/stdin",0),rb("/dev/stdout",1),rb("/dev/stderr",1));cb=!1;Da(sa);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&
(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();ta.unshift(b)}Da(ta)}}if(!(0<L)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)ua();Da(ra);0<L||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();Nb();


  return loadWASM.ready
}

);
})();
export default loadWASM;